configpath: $XDG_CONFIG_HOME/.config/nom/config.yml
showfavourites: true
version: ""
feeds:
    - url: https://codeberg.org/babalark.rss
    - url: https://xkcd.com/rss.xml
    - url: https://blahaj.zone/@linuxenjoyer.rss
ordering: desc
theme:
    glamour: dark
    titleColor: "62"
    filterColor: "62"
    selectedItemColor: "170"
    readIcon: ✓
http:
    mintls: TLS 1.2
